[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[context.production.environment]
  VITE_SUPABASE_URL = "${VITE_SUPABASE_URL}"
  VITE_SUPABASE_ANON_KEY = "${VITE_SUPABASE_ANON_KEY}"
  VITE_TEAMSNAP_CLIENT_ID = "${VITE_TEAMSNAP_CLIENT_ID}"
  VITE_GOOGLE_MAPS_API_KEY = "${VITE_GOOGLE_MAPS_API_KEY}"

[functions]
  node_bundler = "esbuild"