[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[context.production.environment]
  VITE_SUPABASE_URL = "${VITE_SUPABASE_URL}"
  VITE_SUPABASE_ANON_KEY = "${VITE_SUPABASE_ANON_KEY}"
  VITE_TEAMSNAP_CLIENT_ID = "${VITE_TEAMSNAP_CLIENT_ID}"
  VITE_GOOGLE_MAPS_API_KEY = "${VITE_GOOGLE_MAPS_API_KEY}"