# ios/App/Podfile
source 'https://cdn.cocoapods.org/'

platform :ios, '14.0'         # ⬅️ raise this

use_frameworks! :linkage => :static

target 'App' do
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp',                :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorCamera',             :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorFilesystem',         :path => '../../node_modules/@capacitor/filesystem'
  pod 'CapacitorHaptics',            :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard',           :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorPushNotifications',  :path => '../../node_modules/@capacitor/push-notifications'
  pod 'CapacitorSplashScreen',       :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar',          :path => '../../node_modules/@capacitor/status-bar'
  pod 'CapacitorToast',              :path => '../../node_modules/@capacitor/toast'
end

# Force all pods to the same minimum target
post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |c|
      c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'  # ⬅️ match here
    end
  end
end

